//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Resources.Views.Friends {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FriendsTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FriendsTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Resources.Views.Friends.FriendsTexts", typeof(FriendsTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to group.
        /// </summary>
        public static string AddToGroup {
            get {
                return ResourceManager.GetString("AddToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to page.
        /// </summary>
        public static string AddToPage {
            get {
                return ResourceManager.GetString("AddToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All friends.
        /// </summary>
        public static string AllFriends {
            get {
                return ResourceManager.GetString("AllFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot write first.
        /// </summary>
        public static string BotWriteFirst {
            get {
                return ResourceManager.GetString("BotWriteFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming request friendships.
        /// </summary>
        public static string ButtonIncoming {
            get {
                return ResourceManager.GetString("ButtonIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing request friendships.
        /// </summary>
        public static string ButtonOutgoing {
            get {
                return ResourceManager.GetString("ButtonOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed actions.
        /// </summary>
        public static string CompletedActions {
            get {
                return ResourceManager.GetString("CompletedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current friends.
        /// </summary>
        public static string CurrentFriends {
            get {
                return ResourceManager.GetString("CurrentFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this friend.
        /// </summary>
        public static string DeleteConfirmationQuestion {
            get {
                return ResourceManager.GetString("DeleteConfirmationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted friends.
        /// </summary>
        public static string DeletedFriends {
            get {
                return ResourceManager.GetString("DeletedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string FriendsTitle {
            get {
                return ResourceManager.GetString("FriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend write first.
        /// </summary>
        public static string FriendWriteFirst {
            get {
                return ResourceManager.GetString("FriendWriteFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friends found. Enable the function of getting current friends..
        /// </summary>
        public static string NoFriends {
            get {
                return ResourceManager.GetString("NoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages.
        /// </summary>
        public static string NoMessages {
            get {
                return ResourceManager.GetString("NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wink.
        /// </summary>
        public static string Wink {
            get {
                return ResourceManager.GetString("Wink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinkFriends.
        /// </summary>
        public static string WinkFriends {
            get {
                return ResourceManager.GetString("WinkFriends", resourceCulture);
            }
        }
    }
}
