//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Resources.Views.MessageOptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageOptionsTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageOptionsTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Resources.Views.MessageOptions.MessageOptionsTexts", typeof(MessageOptionsTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new message.
        /// </summary>
        public static string AddNewMessage {
            get {
                return ResourceManager.GetString("AddNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After stop words.
        /// </summary>
        public static string AfterStopWords {
            get {
                return ResourceManager.GetString("AfterStopWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot starts talk first.
        /// </summary>
        public static string BotStartsTalkFirst {
            get {
                return ResourceManager.GetString("BotStartsTalkFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If bot starts talking first.
        /// </summary>
        public static string BotStartsTalkingFirst {
            get {
                return ResourceManager.GetString("BotStartsTalkingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If bot starts talking second.
        /// </summary>
        public static string BotStartsTalkingSecond {
            get {
                return ResourceManager.GetString("BotStartsTalkingSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current group.
        /// </summary>
        public static string CurrentGroup {
            get {
                return ResourceManager.GetString("CurrentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group not selected.
        /// </summary>
        public static string GroupNotSelected {
            get {
                return ResourceManager.GetString("GroupNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importancy factor.
        /// </summary>
        public static string ImportancyFactor {
            get {
                return ResourceManager.GetString("ImportancyFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message options.
        /// </summary>
        public static string MessageOptionsTitle {
            get {
                return ResourceManager.GetString("MessageOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of message.
        /// </summary>
        public static string NumberOfMessage {
            get {
                return ResourceManager.GetString("NumberOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to set default messages.
        /// </summary>
        public static string ReturnToDefaultMessage {
            get {
                return ResourceManager.GetString("ReturnToDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All other messages would be removed.
        /// </summary>
        public static string ReturnToDefaultMessage2 {
            get {
                return ResourceManager.GetString("ReturnToDefaultMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default settings.
        /// </summary>
        public static string SetDefaultSettings {
            get {
                return ResourceManager.GetString("SetDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time from.
        /// </summary>
        public static string TimeFrom {
            get {
                return ResourceManager.GetString("TimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to.
        /// </summary>
        public static string TimeTo {
            get {
                return ResourceManager.GetString("TimeTo", resourceCulture);
            }
        }
    }
}
