//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Resources.Views.GroupSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GroupSettingsTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupSettingsTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Resources.Views.GroupSettings.GroupSettingsTexts", typeof(GroupSettingsTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum permissible removal percentage of retired friends.
        /// </summary>
        public static string AllowedRemovalPercentage {
            get {
                return ResourceManager.GetString("AllowedRemovalPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count added in groups in day.
        /// </summary>
        public static string CountAddedInGroupsInDay {
            get {
                return ResourceManager.GetString("CountAddedInGroupsInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count add in groups in hour.
        /// </summary>
        public static string CountAddedInGroupsInHour {
            get {
                return ResourceManager.GetString("CountAddedInGroupsInHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count add in pages in day.
        /// </summary>
        public static string CountAddedInPagesInDay {
            get {
                return ResourceManager.GetString("CountAddedInPagesInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count add in pages in hour.
        /// </summary>
        public static string CountAddedInPagesInHour {
            get {
                return ResourceManager.GetString("CountAddedInPagesInHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count max friends.
        /// </summary>
        public static string CountMaxFriends {
            get {
                return ResourceManager.GetString("CountMaxFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count min friends.
        /// </summary>
        public static string CountMinFriends {
            get {
                return ResourceManager.GetString("CountMinFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend options.
        /// </summary>
        public static string FriendOptions {
            get {
                return ResourceManager.GetString("FriendOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo options.
        /// </summary>
        public static string GeoOptions {
            get {
                return ResourceManager.GetString("GeoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group settings.
        /// </summary>
        public static string GroupSettingsTitle {
            get {
                return ResourceManager.GetString("GroupSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups and pages.
        /// </summary>
        public static string GroupsTitle {
            get {
                return ResourceManager.GetString("GroupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour(s).
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to all groups.
        /// </summary>
        public static string IsJoinToAllGroups {
            get {
                return ResourceManager.GetString("IsJoinToAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits settings.
        /// </summary>
        public static string LimitsSettingsTitle {
            get {
                return ResourceManager.GetString("LimitsSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message options.
        /// </summary>
        public static string MessageOptions {
            get {
                return ResourceManager.GetString("MessageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min(s).
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm every friendship.
        /// </summary>
        public static string RetryTimeConfirmFriendships {
            get {
                return ResourceManager.GetString("RetryTimeConfirmFriendships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get new friends every.
        /// </summary>
        public static string RetryTimeGetNewAndRecommendedFriends {
            get {
                return ResourceManager.GetString("RetryTimeGetNewAndRecommendedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry time join the groups.
        /// </summary>
        public static string RetryTimeJoinGroups {
            get {
                return ResourceManager.GetString("RetryTimeJoinGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable join the groups and pages.
        /// </summary>
        public static string RetryTimeJoinGroupsEnable {
            get {
                return ResourceManager.GetString("RetryTimeJoinGroupsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry time join page.
        /// </summary>
        public static string RetryTimeJoinPage {
            get {
                return ResourceManager.GetString("RetryTimeJoinPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your friends list every.
        /// </summary>
        public static string RetryTimeRefreshFriends {
            get {
                return ResourceManager.GetString("RetryTimeRefreshFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send messages to new friends through.
        /// </summary>
        public static string RetryTimeSendNewFriend {
            get {
                return ResourceManager.GetString("RetryTimeSendNewFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send requests to friends every.
        /// </summary>
        public static string RetryTimeSendRequestFriendships {
            get {
                return ResourceManager.GetString("RetryTimeSendRequestFriendships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer every unanswered posts.
        /// </summary>
        public static string RetryTimeSendUnanswered {
            get {
                return ResourceManager.GetString("RetryTimeSendUnanswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer unread messages every.
        /// </summary>
        public static string RetryTimeSendUnread {
            get {
                return ResourceManager.GetString("RetryTimeSendUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec(s).
        /// </summary>
        public static string Sec {
            get {
                return ResourceManager.GetString("Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra-messages sent through.
        /// </summary>
        public static string UnansweredDelay {
            get {
                return ResourceManager.GetString("UnansweredDelay", resourceCulture);
            }
        }
    }
}
