//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Resources.Views.GroupSettings.WinkFriends {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WinkFriendsTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinkFriendsTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Resources.Views.GroupSettings.WinkFriends.WinkFriendsTexts", typeof(WinkFriendsTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider geo.
        /// </summary>
        public static string ConsiderGeoForWink {
            get {
                return ResourceManager.GetString("ConsiderGeoForWink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wink back.
        /// </summary>
        public static string WinkBack {
            get {
                return ResourceManager.GetString("WinkBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wink friends friends retry time.
        /// </summary>
        public static string WinkFriendsFriendsRetryTime {
            get {
                return ResourceManager.GetString("WinkFriendsFriendsRetryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wink retry time.
        /// </summary>
        public static string WinkRetryTime {
            get {
                return ResourceManager.GetString("WinkRetryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wink options.
        /// </summary>
        public static string WinkTitle {
            get {
                return ResourceManager.GetString("WinkTitle", resourceCulture);
            }
        }
    }
}
